title: Kevina's Website # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcometo my site  
  <br><br>
  <p align="center">
  <a href="https://www.linkedin.com/in/kevina-windy-arlianni-6581271b4/">View My LinkedIn Profile</a> 
    <a href="https://github.com/kevinawindy">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Statistics at Institut Teknologi Sepuluh Nopember.
  <br><br>
  Iâ€™m interested in Data and Statistics. Passionate about studying how to improve performance.
  <br><br>
  </p>

owner:
  name:           Kevina Windy Arlianni
  bio:            Data Science, Data Analytics
  email:          kevina.arlianni@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like
  linkedin: kevina-windy-arlianni
  github: kevinawindy

theme: jekyll-theme-minimal
google_analytics: UA-226920551-1 # your Google Analytics tracking ID here
