title: <p align="center">Kevina's Website </p>

logo: "/images/Picture1.png?raw=true" # your photo (or logo) here

description: > 
  <p align="center">
  <a href="https://www.linkedin.com/in/kevina-windy-arlianni-6581271b4/">LinkedIn</a> 
  <a href="https://github.com/kevinawindy">GitHub</a>
  </p>
  
  <p align="justify">
  Iâ€™m interested in Statistics and Programming
  <br><br>
  I am currently learning in Institut Teknologi Sepuluh Nopember pursuing Statistics Bachelor Degree.
  <br><br>
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-226920551-1 # your Google Analytics tracking ID here
